[workspace]
authors = ["Gian <gian.cercena@greenmountainpower.com>"]
channels = ["conda-forge"]
name = "sf_ml_test"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.4.1,<3"
scikit-learn = ">=1.8.0,<2"
xgboost = ">=3.1.2,<4"
matplotlib = ">=3.10.8,<4"

[pypi-dependencies]
torch = ">=2.9.1, <3"
torchvision = ">=0.24.1, <0.25"
