[workspace]
authors = ["Gian <gian.cercena@greenmountainpower.com>"]
channels = ["conda-forge"]
name = "sf_ml_test"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
scikit-learn = ">=1.6.1,<2"
xgboost = ">=2.1.4,<3"
pytorch = ">=2.4.1,<3"
torchvision = ">=0.19.0,<0.20"
matplotlib = ">=3.9.4,<4"
numpy = ">=2.0.2,<3"
tomli = ">=2.4.0,<3"
black = ">=25.12.0,<26"

[pypi-dependencies]
snowflake-snowpark-python = ">=1.44.0, <2"
snowflake-ml-python = ">=1.23.0, <2"
tomli = ">=2.0.0, <3"
snowflake-connector-python = { version = ">=3.18.0, <4", extras = ["secure-local-storage"] }
